/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package eu.geclipse.batch.model.qdl.validation;

import java.math.BigInteger;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link eu.geclipse.batch.model.qdl.IntegerBoundaryType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntegerBoundaryTypeValidator
{
  boolean validate();

  boolean validateValue(int value);

  boolean validateExclusiveBound(int value);

  boolean validateValue(Integer value);

  boolean validateExclusiveBound(Integer value);

  boolean validateValue(BigInteger value);
  boolean validateExclusiveBound(BigInteger value);
  boolean validateAnyAttribute(FeatureMap value);
}
