/******************************************************************************
 * Copyright (c) 2008 g-Eclipse consortium
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Initial development of the original code was made for
 * project g-Eclipse founded by European Union
 * project number: FP6-IST-034327  http://www.geclipse.eu/
 *
 * Contributor(s):
 *     UCY (http://www.ucy.cs.ac.cy)
 *      - Nicholas Loulloudes (loulloudes.n@cs.ucy.ac.cy)
 *
  *****************************************************************************/
package eu.geclipse.batch.model.qdl.validation;

import eu.geclipse.batch.model.qdl.AllowedVirtualOrganizationsType;
import eu.geclipse.batch.model.qdl.QueueStatusEnumeration;
import eu.geclipse.batch.model.qdl.QueueTypeEnumeration;
import eu.geclipse.batch.model.qdl.RangeValueType;

/**
 * A sample validator interface for {@link eu.geclipse.batch.model.qdl.QueueType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QueueTypeValidator
{
  boolean validate();

  boolean validateQueueName(String value);
  boolean validateDescription(String value);
  boolean validateQueueType(QueueTypeEnumeration value);
  boolean validateQueueStatus(QueueStatusEnumeration value);
  boolean validateCPUTimeLimit(RangeValueType value);
  boolean validateWallTimeLimit(RangeValueType value);
  boolean validateAllowedVirtualOrganizations(AllowedVirtualOrganizationsType value);
  boolean validatePriority(RangeValueType value);
  boolean validateRunningJobs(RangeValueType value);
  boolean validateJobsInQueue(RangeValueType value);
  boolean validateAssignedResources(RangeValueType value);
}
