/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package eu.geclipse.batch.model.qdl.validation;

import eu.geclipse.batch.model.qdl.AllowedVirtualOrganizationsType;
import eu.geclipse.batch.model.qdl.QueueStatusEnumeration;
import eu.geclipse.batch.model.qdl.QueueTypeEnumeration;
import eu.geclipse.batch.model.qdl.RangeValueType;

/**
 * A sample validator interface for {@link eu.geclipse.batch.model.qdl.QueueType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QueueTypeValidator
{
  boolean validate();

  boolean validateQueueName(String value);
  boolean validateDescription(String value);
  boolean validateQueueType(QueueTypeEnumeration value);
  boolean validateQueueStatus(QueueStatusEnumeration value);
  boolean validateCPUTimeLimit(RangeValueType value);
  boolean validateWallTimeLimit(RangeValueType value);
  boolean validateAllowedVirtualOrganizations(AllowedVirtualOrganizationsType value);
  boolean validatePriority(RangeValueType value);
  boolean validateRunningJobs(RangeValueType value);
  boolean validateJobsInQueue(RangeValueType value);
  boolean validateAssignedResources(RangeValueType value);
}
