/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package eu.geclipse.batch.model.qdl.validation;

import eu.geclipse.batch.model.qdl.BoundaryType;
import eu.geclipse.batch.model.qdl.ExactType;
import eu.geclipse.batch.model.qdl.RangeType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link eu.geclipse.batch.model.qdl.RangeValueType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RangeValueTypeValidator
{
  boolean validate();

  boolean validateUpperBoundedRange(BoundaryType value);
  boolean validateLowerBoundedRange(BoundaryType value);
  boolean validateExact(EList<ExactType> value);
  boolean validateRange(EList<RangeType> value);
  boolean validateAnyAttribute(FeatureMap value);
}
