/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package eu.geclipse.jsdl.model.base.validation;

import eu.geclipse.jsdl.model.base.ApplicationType;
import eu.geclipse.jsdl.model.base.JobIdentificationType;
import eu.geclipse.jsdl.model.base.ResourcesType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link eu.geclipse.jsdl.model.base.JobDescriptionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JobDescriptionTypeValidator
{
  boolean validate();

  boolean validateJobIdentification(JobIdentificationType value);
  boolean validateApplication(ApplicationType value);
  boolean validateResources(ResourcesType value);
  boolean validateDataStaging(EList value);
  boolean validateAny(FeatureMap value);
  boolean validateAnyAttribute(FeatureMap value);
}
