/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package eu.geclipse.jsdl.model.validation;

import eu.geclipse.jsdl.model.CreationFlagEnumeration;
import eu.geclipse.jsdl.model.SourceTargetType;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link eu.geclipse.jsdl.model.DataStagingType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataStagingTypeValidator
{
  boolean validate();

  boolean validateFileName(String value);
  boolean validateFilesystemName(String value);
  boolean validateCreationFlag(CreationFlagEnumeration value);
  boolean validateDeleteOnTermination(boolean value);
  boolean validateSource(SourceTargetType value);
  boolean validateTarget(SourceTargetType value);
  boolean validateAny(FeatureMap value);
  boolean validateName(String value);
  boolean validateAnyAttribute(FeatureMap value);
}
