/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package eu.geclipse.jsdl.model.functions.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link eu.geclipse.jsdl.model.functions.ExceptionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExceptionTypeValidator
{
  boolean validate();

  boolean validateValue(BigInteger value);
}
