/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package eu.geclipse.jsdl.model.functions.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.geclipse.jsdl.model.functions.LoopType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoopTypeValidator
{
  boolean validate();

  boolean validateException(EList value);
  boolean validateEnd(BigInteger value);
  boolean validateStart(BigInteger value);
  boolean validateStep(BigInteger value);
}
